# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

invtridiag <- function(A) {
    .Call(`_BGdvs_invtridiag`, A)
}

invtridiag_memo <- function(dvec, od, n) {
    .Call(`_BGdvs_invtridiag_memo`, dvec, od, n)
}

getQuantitiesCpp <- function(A, B, nb, bl) {
    .Call(`_BGdvs_getQuantitiesCpp`, A, B, nb, bl)
}

getXX <- function(mu_q_gamma, X, mu_q_s2inv) {
    .Call(`_BGdvs_getXX`, mu_q_gamma, X, mu_q_s2inv)
}

